version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker check
          command: |
            set -e
            env
